const IN_PROGRESS = "IN_PROGRESS";
const COMPLETED = "COMPLETED";
const PICKED_UP = "PICKED_UP";
const CANCELED = "CANCELED";

export const STATUSES = Object.freeze({
  IN_PROGRESS,
  COMPLETED,
  PICKED_UP,
  CANCELED,
});
